//> using scala "3.3.3"
//> using dep "dev.zio::zio:2.1.1"
//> using test.dep "dev.zio::zio-test:2.1.1"
//> using test.dep "dev.zio::zio-test-sbt:2.1.1"
//> using test.dep "dev.zio::zio-test-magnolia:2.1.1"
